In [32]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score,f1_score,recall_score,classification_report, confusion_matrix
from sklearn.feature_selection import chi2,SelectKBest,mutual_info_classif,RFE

In [4]:
df=pd.read_csv(r"C:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\data\medical_disease_data_cleaning.csv")
df

      Age  Gender   BMI  ...  PhysicalActivity  FamilyHistory  Disease
0      23       1  17.5  ...                 2              0        1
1      69       1  31.1  ...                 0              1        4
2      61       0  31.3  ...                 2              0        1
3      47       0  23.9  ...                 1              0        1
4      47       1  28.3  ...                 0              0        1
...   ...     ...   ...  ...               ...            ...      ...
9995   49       1  27.1  ...                 0              0        3
9996   84       1  29.2  ...                 0              1        3
9997   41       1  22.8  ...                 2              1        3
9998   55       1  29.0  ...                 2              1        4
9999   59       1  32.2  ...                 0              1        4

[10000 rows x 12 columns]

## divide data in input featuers and target

In [12]:
x=df.drop('Disease',axis=1)
y=df["Disease"]

In [10]:
x

      Age  Gender   BMI  ...  Alcohol  PhysicalActivity  FamilyHistory
0      23       1  17.5  ...        0                 2              0
1      69       1  31.1  ...        0                 0              1
2      61       0  31.3  ...        0                 2              0
3      47       0  23.9  ...        0                 1              0
4      47       1  28.3  ...        1                 0              0
...   ...     ...   ...  ...      ...               ...            ...
9995   49       1  27.1  ...        0                 0              0
9996   84       1  29.2  ...        1                 0              1
9997   41       1  22.8  ...        0                 2              1
9998   55       1  29.0  ...        0                 2              1
9999   59       1  32.2  ...        0                 0              1

[10000 rows x 11 columns]

In [11]:
y

      Disease
0           1
1           4
2           1
3           1
4           1
...       ...
9995        3
9996        3
9997        3
9998        4
9999        4

[10000 rows x 1 columns]

## spliting data in training and testing

In [14]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8000, 11), (2000, 11), (8000,), (2000,))

## Select best features using feature selection techniques

#### 1. Chi2

In [16]:
chi_score, p_value=chi2(x_train,y_train)
chi_result = pd.DataFrame({
    'Feature': x_train.columns,
    'Chi2_Score': chi_score,
    'P_Value': p_value
})


print(chi_result.sort_values('Chi2_Score',ascending=False))

             Feature   Chi2_Score       P_Value
4       GlucoseLevel  9637.292780  0.000000e+00
5        Cholesterol  7352.598335  0.000000e+00
0                Age  2748.205505  0.000000e+00
3      BloodPressure  2335.595129  0.000000e+00
7            Smoking   384.171284  7.311655e-82
10     FamilyHistory   350.236034  1.559608e-74
2                BMI   263.208461  9.280391e-56
6          HeartRate     7.041426  1.337152e-01
8            Alcohol     6.180366  1.860772e-01
9   PhysicalActivity     0.477781  9.756277e-01
1             Gender     0.398869  9.825694e-01

### 2. mutual information

In [17]:
mi_score=mutual_info_classif(x_train,y_train)
mi_result=pd.DataFrame({
    'Feature':x_train.columns,
    'MI_Score':mi_score
})


print(mi_result.sort_values('MI_Score',ascending=False))

             Feature  MI_Score
2                BMI  0.048798
4       GlucoseLevel  0.044043
5        Cholesterol  0.039575
7            Smoking  0.039024
0                Age  0.037017
10     FamilyHistory  0.029766
3      BloodPressure  0.026365
9   PhysicalActivity  0.008037
8            Alcohol  0.000890
1             Gender  0.000000
6          HeartRate  0.000000

### Select best 8 features using Chi2 and SelectKBest(Filter Method)

In [18]:
selector= SelectKBest(score_func=chi2,k=8)
x_train_chi =selector.fit_transform(x_train,y_train)
x_test_chi=selector.transform(x_test)


selected_features = x_train.columns[selector.get_support()]

selected_col=pd.DataFrame({
    'Features':selected_features
})
print("Selected Features:\n")

print(selected_col)

Selected Features:

        Features
0            Age
1            BMI
2  BloodPressure
3   GlucoseLevel
4    Cholesterol
5      HeartRate
6        Smoking
7  FamilyHistory

### Select best 8 features using RFE (Recursive Feature Elimination - Wrapper Method)

In [24]:
model =RandomForestClassifier()
rfe = RFE(estimator=model,n_features_to_select=8)
rfe.fit(x_train,y_train)

RFE(estimator=RandomForestClassifier(), n_features_to_select=8)

In [ ]:
## features  ranking using RFE

rfe_result = pd.DataFrame({
    "features_name": x_train.columns,
    "Features_Ranking": rfe.ranking_
})

print(rfe_result.sort_values("Features_Ranking",ascending=True))

       features_name  Features_Ranking
0                Age                 1
2                BMI                 1
3      BloodPressure                 1
4       GlucoseLevel                 1
6          HeartRate                 1
5        Cholesterol                 1
7            Smoking                 1
10     FamilyHistory                 1
9   PhysicalActivity                 2
1             Gender                 3
8            Alcohol                 4

In [ ]:
### Selected Features using RFE

selected_features_rfe = pd.DataFrame({
    "Features": x_train.columns[rfe.support_]
    })

print(selected_features_rfe)

        Features
0            Age
1            BMI
2  BloodPressure
3   GlucoseLevel
4    Cholesterol
5      HeartRate
6        Smoking
7  FamilyHistory

In [27]:
x_train_rfe = rfe.transform(x_train)
x_test_rfe = rfe.transform(x_test)

print(x_train_rfe.shape)
print(x_test_rfe.shape)

(8000, 8)
(2000, 8)

## Now Train the model

#### 👉  Train and Evaluate Model using Chi2 Selected Features

In [ ]:
models={
    "👉 logistic_regression":LogisticRegression(),
    "👉 decision_tree":DecisionTreeClassifier(),   
    "👉 random_forest":RandomForestClassifier(),
    "👉 svm":SVC(),
    "👉 knn":KNeighborsClassifier()
}

In [42]:
for name, model in models.items():
    model.fit(x_train_chi, y_train)
    y_pred_chi = model.predict(x_test_chi)

    print("\n",name)

    print("Accuracy Score_chi:", accuracy_score(y_test, y_pred_chi))
    print("precision score_chi:", precision_score(y_test, y_pred_chi,average='weighted'))
    print("Recall Score_chi:", recall_score(y_test, y_pred_chi,average='weighted'))
    print("F1 Score_chi:", f1_score(y_test, y_pred_chi,average='weighted'))
    print("Confusion Matrix_chi:\n", confusion_matrix(y_test, y_pred_chi))
    print("Classification Report_chi:\n", classification_report(y_test, y_pred_chi))

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

 👉 logistic_regression
Accuracy Score_chi: 0.6415
precision score_chi: 0.4753435572865953
Recall Score_chi: 0.6415
F1 Score_chi: 0.528340280725779
Confusion Matrix_chi:
 [[   0   34    0   12    0]
 [   0 1252    0   27    0]
 [   0   42    0   11    0]
 [   0  325    0   31    0]
 [   0  243    0   23    0]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.66      0.98      0.79      1279
           2       0.00      0.00      0.00        53
           3       0.30      0.09      0.13       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.19      0.21      0.18      2000
weighted avg       0.48      0.64      0.53      2000


 👉 decision_tree
Accuracy Score_chi: 0.655
precision score_chi: 0.6534217269600809
Recall Score_chi: 0.655
F1 Score_chi: 0.6539239754797874
Confusion Matrix_chi:
 [[  14    0   17   12    3]
 [   1 1079    0  101   98]
 [  11    8    5   26    3]
 [   6  104   18  128  100]
 [   2   94    3   83   84]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.41      0.30      0.35        46
           1       0.84      0.84      0.84      1279
           2       0.12      0.09      0.10        53
           3       0.37      0.36      0.36       356
           4       0.29      0.32      0.30       266

    accuracy                           0.66      2000
   macro avg       0.41      0.38      0.39      2000
weighted avg       0.65      0.66      0.65      2000


 👉 random_forest
Accuracy Score_chi: 0.667
precision score_chi: 0.6247035467815362
Recall Score_chi: 0.667
F1 Score_chi: 0.6392610495906597
Confusion Matrix_chi:
 [[   7    0    5   34    0]
 [   0 1145    0   76   58]
 [   4    1    5   43    0]
 [   8  155    7  132   54]
 [   0  152    0   69   45]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.37      0.15      0.22        46
           1       0.79      0.90      0.84      1279
           2       0.29      0.09      0.14        53
           3       0.37      0.37      0.37       356
           4       0.29      0.17      0.21       266

    accuracy                           0.67      2000
   macro avg       0.42      0.34      0.36      2000
weighted avg       0.62      0.67      0.64      2000


 👉 svm
Accuracy Score_chi: 0.639
precision score_chi: 0.40945941883767534
Recall Score_chi: 0.639
F1 Score_chi: 0.49910290076335884
Confusion Matrix_chi:
 [[   0   44    0    2    0]
 [   0 1278    0    1    0]
 [   0   52    0    1    0]
 [   0  356    0    0    0]
 [   0  266    0    0    0]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.64      1.00      0.78      1279
           2       0.00      0.00      0.00        53
           3       0.00      0.00      0.00       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.13      0.20      0.16      2000
weighted avg       0.41      0.64      0.50      2000


 👉 knn
Accuracy Score_chi: 0.6235
precision score_chi: 0.5473225466759306
Recall Score_chi: 0.6235
F1 Score_chi: 0.5728889652828223
Confusion Matrix_chi:
 [[   6   13    3   19    5]
 [   9 1141    7   80   42]
 [   2   26    3   18    4]
 [   6  230    9   74   37]
 [   3  195    4   41   23]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.23      0.13      0.17        46
           1       0.71      0.89      0.79      1279
           2       0.12      0.06      0.08        53
           3       0.32      0.21      0.25       356
           4       0.21      0.09      0.12       266

    accuracy                           0.62      2000
   macro avg       0.32      0.27      0.28      2000
weighted avg       0.55      0.62      0.57      2000

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### ## Train and Evaluate Model using RFE Selected Features

In [43]:
for name, model in models.items():
    model.fit(x_train_rfe, y_train)
    y_pred_rfe = model.predict(x_test_rfe)

    print("\n",name)

    print("Accuracy Score_rfe:", accuracy_score(y_test, y_pred_rfe))
    print("precision score_rfe:", precision_score(y_test, y_pred_rfe,average='weighted'))
    print("Recall Score_rfe:", recall_score(y_test, y_pred_rfe,average='weighted'))
    print("F1 Score_rfe:", f1_score(y_test, y_pred_rfe,average='weighted'))
    print("Confusion Matrix_rfe:\n", confusion_matrix(y_test, y_pred_rfe))
    print("Classification Report_rfe:\n", classification_report(y_test, y_pred_rfe))

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

 👉 logistic_regression
Accuracy Score_rfe: 0.6415
precision score_rfe: 0.4753435572865953
Recall Score_rfe: 0.6415
F1 Score_rfe: 0.528340280725779
Confusion Matrix_rfe:
 [[   0   34    0   12    0]
 [   0 1252    0   27    0]
 [   0   42    0   11    0]
 [   0  325    0   31    0]
 [   0  243    0   23    0]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.66      0.98      0.79      1279
           2       0.00      0.00      0.00        53
           3       0.30      0.09      0.13       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.19      0.21      0.18      2000
weighted avg       0.48      0.64      0.53      2000


 👉 decision_tree
Accuracy Score_rfe: 0.6515
precision score_rfe: 0.6505190003335853
Recall Score_rfe: 0.6515
F1 Score_rfe: 0.6507853286742826
Confusion Matrix_rfe:
 [[  16    0   14   13    3]
 [   0 1079    0   98  102]
 [  13    7    7   23    3]
 [   9  103   16  123  105]
 [   2   94    2   90   78]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.40      0.35      0.37        46
           1       0.84      0.84      0.84      1279
           2       0.18      0.13      0.15        53
           3       0.35      0.35      0.35       356
           4       0.27      0.29      0.28       266

    accuracy                           0.65      2000
   macro avg       0.41      0.39      0.40      2000
weighted avg       0.65      0.65      0.65      2000


 👉 random_forest
Accuracy Score_rfe: 0.668
precision score_rfe: 0.6301778695556174
Recall Score_rfe: 0.668
F1 Score_rfe: 0.6437855751132553
Confusion Matrix_rfe:
 [[   9    0    7   30    0]
 [   0 1145    0   77   57]
 [   5    1    5   42    0]
 [   9  154    5  121   67]
 [   0  139    0   71   56]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.39      0.20      0.26        46
           1       0.80      0.90      0.84      1279
           2       0.29      0.09      0.14        53
           3       0.35      0.34      0.35       356
           4       0.31      0.21      0.25       266

    accuracy                           0.67      2000
   macro avg       0.43      0.35      0.37      2000
weighted avg       0.63      0.67      0.64      2000


 👉 svm
Accuracy Score_rfe: 0.639
precision score_rfe: 0.40945941883767534
Recall Score_rfe: 0.639
F1 Score_rfe: 0.49910290076335884
Confusion Matrix_rfe:
 [[   0   44    0    2    0]
 [   0 1278    0    1    0]
 [   0   52    0    1    0]
 [   0  356    0    0    0]
 [   0  266    0    0    0]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.64      1.00      0.78      1279
           2       0.00      0.00      0.00        53
           3       0.00      0.00      0.00       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.13      0.20      0.16      2000
weighted avg       0.41      0.64      0.50      2000


 👉 knn
Accuracy Score_rfe: 0.6235
precision score_rfe: 0.5473225466759306
Recall Score_rfe: 0.6235
F1 Score_rfe: 0.5728889652828223
Confusion Matrix_rfe:
 [[   6   13    3   19    5]
 [   9 1141    7   80   42]
 [   2   26    3   18    4]
 [   6  230    9   74   37]
 [   3  195    4   41   23]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.23      0.13      0.17        46
           1       0.71      0.89      0.79      1279
           2       0.12      0.06      0.08        53
           3       0.32      0.21      0.25       356
           4       0.21      0.09      0.12       266

    accuracy                           0.62      2000
   macro avg       0.32      0.27      0.28      2000
weighted avg       0.55      0.62      0.57      2000

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

## Handling Class Imbalance

In [44]:
models={
    "👉 logistic_regression":LogisticRegression(),
    "👉 decision_tree":DecisionTreeClassifier(random_state=42,class_weight='balanced'),   
    "👉 random_forest":RandomForestClassifier(random_state=42,class_weight='balanced'),
    "👉 svm":SVC(),
    "👉 knn":KNeighborsClassifier()
}

### Model Training using Chi-Square Selected Features

In [45]:
for name, model in models.items():
    model.fit(x_train_chi, y_train)
    y_pred_chi = model.predict(x_test_chi)

    print("\n",name)

    print("Accuracy Score_chi:", accuracy_score(y_test, y_pred_chi))
    print("precision score_chi:", precision_score(y_test, y_pred_chi,average='weighted'))
    print("Recall Score_chi:", recall_score(y_test, y_pred_chi,average='weighted'))
    print("F1 Score_chi:", f1_score(y_test, y_pred_chi,average='weighted'))
    print("Confusion Matrix_chi:\n", confusion_matrix(y_test, y_pred_chi))
    print("Classification Report_chi:\n", classification_report(y_test, y_pred_chi))

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

 👉 logistic_regression
Accuracy Score_chi: 0.6415
precision score_chi: 0.4753435572865953
Recall Score_chi: 0.6415
F1 Score_chi: 0.528340280725779
Confusion Matrix_chi:
 [[   0   34    0   12    0]
 [   0 1252    0   27    0]
 [   0   42    0   11    0]
 [   0  325    0   31    0]
 [   0  243    0   23    0]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.66      0.98      0.79      1279
           2       0.00      0.00      0.00        53
           3       0.30      0.09      0.13       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.19      0.21      0.18      2000
weighted avg       0.48      0.64      0.53      2000


 👉 decision_tree
Accuracy Score_chi: 0.658
precision score_chi: 0.6547219431950854
Recall Score_chi: 0.658
F1 Score_chi: 0.6563051564259224
Confusion Matrix_chi:
 [[  14    4   12   12    4]
 [   1 1087    1   96   94]
 [  14    3   10   22    4]
 [  19  111   20  123   83]
 [   1   86    3   94   82]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.29      0.30      0.29        46
           1       0.84      0.85      0.85      1279
           2       0.22      0.19      0.20        53
           3       0.35      0.35      0.35       356
           4       0.31      0.31      0.31       266

    accuracy                           0.66      2000
   macro avg       0.40      0.40      0.40      2000
weighted avg       0.65      0.66      0.66      2000


 👉 random_forest
Accuracy Score_chi: 0.665
precision score_chi: 0.7365198016219666
Recall Score_chi: 0.665
F1 Score_chi: 0.6911274555093251
Confusion Matrix_chi:
 [[  19    0    9   17    1]
 [   0 1006    0  131  142]
 [  12    0    8   32    1]
 [  15   18   12  178  133]
 [   0   24    0  123  119]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.41      0.41      0.41        46
           1       0.96      0.79      0.86      1279
           2       0.28      0.15      0.20        53
           3       0.37      0.50      0.43       356
           4       0.30      0.45      0.36       266

    accuracy                           0.67      2000
   macro avg       0.46      0.46      0.45      2000
weighted avg       0.74      0.67      0.69      2000


 👉 svm
Accuracy Score_chi: 0.639
precision score_chi: 0.40945941883767534
Recall Score_chi: 0.639
F1 Score_chi: 0.49910290076335884
Confusion Matrix_chi:
 [[   0   44    0    2    0]
 [   0 1278    0    1    0]
 [   0   52    0    1    0]
 [   0  356    0    0    0]
 [   0  266    0    0    0]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.64      1.00      0.78      1279
           2       0.00      0.00      0.00        53
           3       0.00      0.00      0.00       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.13      0.20      0.16      2000
weighted avg       0.41      0.64      0.50      2000


 👉 knn
Accuracy Score_chi: 0.6235
precision score_chi: 0.5473225466759306
Recall Score_chi: 0.6235
F1 Score_chi: 0.5728889652828223
Confusion Matrix_chi:
 [[   6   13    3   19    5]
 [   9 1141    7   80   42]
 [   2   26    3   18    4]
 [   6  230    9   74   37]
 [   3  195    4   41   23]]
Classification Report_chi:
               precision    recall  f1-score   support

           0       0.23      0.13      0.17        46
           1       0.71      0.89      0.79      1279
           2       0.12      0.06      0.08        53
           3       0.32      0.21      0.25       356
           4       0.21      0.09      0.12       266

    accuracy                           0.62      2000
   macro avg       0.32      0.27      0.28      2000
weighted avg       0.55      0.62      0.57      2000

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### Model Training using RFE Selected Features

In [46]:
for name, model in models.items():
    model.fit(x_train_rfe, y_train)
    y_pred_rfe = model.predict(x_test_rfe)

    print("\n",name)

    print("Accuracy Score_rfe:", accuracy_score(y_test, y_pred_rfe))
    print("precision score_rfe:", precision_score(y_test, y_pred_rfe,average='weighted'))
    print("Recall Score_rfe:", recall_score(y_test, y_pred_rfe,average='weighted'))
    print("F1 Score_rfe:", f1_score(y_test, y_pred_rfe,average='weighted'))
    print("Confusion Matrix_rfe:\n", confusion_matrix(y_test, y_pred_rfe))
    print("Classification Report_rfe:\n", classification_report(y_test, y_pred_rfe))

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

 👉 logistic_regression
Accuracy Score_rfe: 0.6415
precision score_rfe: 0.4753435572865953
Recall Score_rfe: 0.6415
F1 Score_rfe: 0.528340280725779
Confusion Matrix_rfe:
 [[   0   34    0   12    0]
 [   0 1252    0   27    0]
 [   0   42    0   11    0]
 [   0  325    0   31    0]
 [   0  243    0   23    0]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.66      0.98      0.79      1279
           2       0.00      0.00      0.00        53
           3       0.30      0.09      0.13       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.19      0.21      0.18      2000
weighted avg       0.48      0.64      0.53      2000


 👉 decision_tree
Accuracy Score_rfe: 0.658
precision score_rfe: 0.6547219431950854
Recall Score_rfe: 0.658
F1 Score_rfe: 0.6563051564259224
Confusion Matrix_rfe:
 [[  14    4   12   12    4]
 [   1 1087    1   96   94]
 [  14    3   10   22    4]
 [  19  111   20  123   83]
 [   1   86    3   94   82]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.29      0.30      0.29        46
           1       0.84      0.85      0.85      1279
           2       0.22      0.19      0.20        53
           3       0.35      0.35      0.35       356
           4       0.31      0.31      0.31       266

    accuracy                           0.66      2000
   macro avg       0.40      0.40      0.40      2000
weighted avg       0.65      0.66      0.66      2000


 👉 random_forest
Accuracy Score_rfe: 0.665
precision score_rfe: 0.7365198016219666
Recall Score_rfe: 0.665
F1 Score_rfe: 0.6911274555093251
Confusion Matrix_rfe:
 [[  19    0    9   17    1]
 [   0 1006    0  131  142]
 [  12    0    8   32    1]
 [  15   18   12  178  133]
 [   0   24    0  123  119]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.41      0.41      0.41        46
           1       0.96      0.79      0.86      1279
           2       0.28      0.15      0.20        53
           3       0.37      0.50      0.43       356
           4       0.30      0.45      0.36       266

    accuracy                           0.67      2000
   macro avg       0.46      0.46      0.45      2000
weighted avg       0.74      0.67      0.69      2000


 👉 svm
Accuracy Score_rfe: 0.639
precision score_rfe: 0.40945941883767534
Recall Score_rfe: 0.639
F1 Score_rfe: 0.49910290076335884
Confusion Matrix_rfe:
 [[   0   44    0    2    0]
 [   0 1278    0    1    0]
 [   0   52    0    1    0]
 [   0  356    0    0    0]
 [   0  266    0    0    0]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.64      1.00      0.78      1279
           2       0.00      0.00      0.00        53
           3       0.00      0.00      0.00       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.13      0.20      0.16      2000
weighted avg       0.41      0.64      0.50      2000


 👉 knn
Accuracy Score_rfe: 0.6235
precision score_rfe: 0.5473225466759306
Recall Score_rfe: 0.6235
F1 Score_rfe: 0.5728889652828223
Confusion Matrix_rfe:
 [[   6   13    3   19    5]
 [   9 1141    7   80   42]
 [   2   26    3   18    4]
 [   6  230    9   74   37]
 [   3  195    4   41   23]]
Classification Report_rfe:
               precision    recall  f1-score   support

           0       0.23      0.13      0.17        46
           1       0.71      0.89      0.79      1279
           2       0.12      0.06      0.08        53
           3       0.32      0.21      0.25       356
           4       0.21      0.09      0.12       266

    accuracy                           0.62      2000
   macro avg       0.32      0.27      0.28      2000
weighted avg       0.55      0.62      0.57      2000

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

### Model Training using All Features

In [47]:
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    print("\n",name)

    print("Accuracy Score:", accuracy_score(y_test, y_pred))
    print("precision score:", precision_score(y_test, y_pred,average='weighted'))
    print("Recall Score:", recall_score(y_test, y_pred,average='weighted'))
    print("F1 Score:", f1_score(y_test, y_pred,average='weighted'))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

 👉 logistic_regression
Accuracy Score: 0.6415
precision score: 0.4668518897414038
Recall Score: 0.6415
F1 Score: 0.5138076901129983
Confusion Matrix:
 [[   0   37    0    9    0]
 [   0 1270    0    9    0]
 [   0   47    0    6    0]
 [   0  343    0   13    0]
 [   0  258    0    8    0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.65      0.99      0.79      1279
           2       0.00      0.00      0.00        53
           3       0.29      0.04      0.06       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.19      0.21      0.17      2000
weighted avg       0.47      0.64      0.51      2000


 👉 decision_tree
Accuracy Score: 0.6365
precision score: 0.6347332912207181
Recall Score: 0.6365
F1 Score: 0.6355054443561928
Confusion Matrix:
 [[  14    6   12    8    6]
 [   1 1067    7  105   99]
 [  14    3    7   23    6]
 [  22  116   18  110   90]
 [   2   95    6   88   75]]
Classification Report:
               precision    recall  f1-score   support

           0       0.26      0.30      0.28        46
           1       0.83      0.83      0.83      1279
           2       0.14      0.13      0.14        53
           3       0.33      0.31      0.32       356
           4       0.27      0.28      0.28       266

    accuracy                           0.64      2000
   macro avg       0.37      0.37      0.37      2000
weighted avg       0.63      0.64      0.64      2000


 👉 random_forest
Accuracy Score: 0.6615
precision score: 0.7267707605883014
Recall Score: 0.6615
F1 Score: 0.6855116552594835
Confusion Matrix:
 [[  17    0    9   19    1]
 [   0 1007    1  135  136]
 [  10    0    7   35    1]
 [  14   26   11  178  127]
 [   0   30    0  122  114]]
Classification Report:
               precision    recall  f1-score   support

           0       0.41      0.37      0.39        46
           1       0.95      0.79      0.86      1279
           2       0.25      0.13      0.17        53
           3       0.36      0.50      0.42       356
           4       0.30      0.43      0.35       266

    accuracy                           0.66      2000
   macro avg       0.46      0.44      0.44      2000
weighted avg       0.73      0.66      0.69      2000


 👉 svm
Accuracy Score: 0.6395
precision score: 0.40896024999999997
Recall Score: 0.6395
F1 Score: 0.49888411100945407
Confusion Matrix:
 [[   0   46    0    0    0]
 [   0 1279    0    0    0]
 [   0   53    0    0    0]
 [   0  356    0    0    0]
 [   0  266    0    0    0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        46
           1       0.64      1.00      0.78      1279
           2       0.00      0.00      0.00        53
           3       0.00      0.00      0.00       356
           4       0.00      0.00      0.00       266

    accuracy                           0.64      2000
   macro avg       0.13      0.20      0.16      2000
weighted avg       0.41      0.64      0.50      2000


 👉 knn
Accuracy Score: 0.624
precision score: 0.5476568300903635
Recall Score: 0.624
F1 Score: 0.5731779834393924
Confusion Matrix:
 [[   6   13    3   19    5]
 [   8 1142    7   81   41]
 [   2   26    3   18    4]
 [   6  230    9   74   37]
 [   3  195    4   41   23]]
Classification Report:
               precision    recall  f1-score   support

           0       0.24      0.13      0.17        46
           1       0.71      0.89      0.79      1279
           2       0.12      0.06      0.08        53
           3       0.32      0.21      0.25       356
           4       0.21      0.09      0.12       266

    accuracy                           0.62      2000
   macro avg       0.32      0.27      0.28      2000
weighted avg       0.55      0.62      0.57      2000

c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\RIya\Desktop\6month-Data-Science\machine learning\medical\medical_project\medical\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

## Final model training

In [56]:
final_model=random_forest=RandomForestClassifier(random_state=42,class_weight='balanced')
final_model.fit(x_train_chi, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [ ]:
final_y_pred = final_model.predict(x_test_chi)

In [ ]:


print("Accuracy Score_final:", accuracy_score(y_test, final_y_pred))
print("precision score_final:", precision_score(y_test, final_y_pred,average='weighted'))
print("Recall Score_final:", recall_score(y_test, final_y_pred,average='weighted'))
print("F1 Score_final:", f1_score(y_test, final_y_pred,average='weighted'))
print("Confusion Matrix_final:\n", confusion_matrix(y_test, final_y_pred))
print("Classification Report_final:\n", classification_report(y_test, final_y_pred))

Accuracy Score_final: 0.665
precision score_final: 0.7365198016219666
Recall Score_final: 0.665
F1 Score_final: 0.6911274555093251
Confusion Matrix_final:
 [[  19    0    9   17    1]
 [   0 1006    0  131  142]
 [  12    0    8   32    1]
 [  15   18   12  178  133]
 [   0   24    0  123  119]]
Classification Report_final:
               precision    recall  f1-score   support

           0       0.41      0.41      0.41        46
           1       0.96      0.79      0.86      1279
           2       0.28      0.15      0.20        53
           3       0.37      0.50      0.43       356
           4       0.30      0.45      0.36       266

    accuracy                           0.67      2000
   macro avg       0.46      0.46      0.45      2000
weighted avg       0.74      0.67      0.69      2000

In [57]:
import joblib
moodel=joblib.dump(final_model, 'medical_disease_prediction_model.lb')